@baseUrl = http://localhost:8000
@apiUrl = {{baseUrl}}/api/populations

### Get all the populations
# @name GetAllPopulations
GET {{apiUrl}}/all

### Get a specific population
# @name GetPopulation
GET {{apiUrl}}/?experiment_name=Experiment+A

### Select a population
@populationId = {{GetPopulation.response.body.$.0.id}}

### Select a population by ID
# @name GetPopulationById
GET {{apiUrl}}/id/{{populationId}}

### Get all associated experiments by population ID
# @name GetExperimentsByPopulationId
GET {{apiUrl}}/id/{{populationId}}/experiments

### Create a new population
# @name CreatePopulation
POST {{apiUrl}}
Content-Type: application/json

{
    "population_name": "Test Population Z",
    "population_type": "diversity_panel",
    "species": "Zea mays",
    "population_info": {
        "description": "Test Description Z"
    },
    "experiment_name": "Experiment B"
}

###
@createdPopulationId = {{CreatePopulation.response.body.id}}

### Update a population
# @name UpdatePopulation
PATCH {{apiUrl}}/id/{{createdPopulationId}}
Content-Type: application/json

{
    "population_name": "Updated Population Z",
    "population_type": "ril",
    "population_info": {
        "description": "Updated Description Z"
    }
}

### Delete a population
# @name DeletePopulation
DELETE {{apiUrl}}/id/{{createdPopulationId}}
