/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariantsIndexRouteImport } from './routes/variants/index'
import { Route as TraitsIndexRouteImport } from './routes/traits/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SensorsIndexRouteImport } from './routes/sensors/index'
import { Route as SensorPlatformsIndexRouteImport } from './routes/sensor-platforms/index'
import { Route as SeasonsIndexRouteImport } from './routes/seasons/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as ProceduresIndexRouteImport } from './routes/procedures/index'
import { Route as PopulationsIndexRouteImport } from './routes/populations/index'
import { Route as PlotsIndexRouteImport } from './routes/plots/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as LinesIndexRouteImport } from './routes/lines/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as GenotypingStudiesIndexRouteImport } from './routes/genotyping-studies/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as AccessionsIndexRouteImport } from './routes/accessions/index'
import { Route as VariantsVariantIdRouteImport } from './routes/variants/$variantId'
import { Route as TraitsTraitIdRouteImport } from './routes/traits/$traitId'
import { Route as SitesSiteIdRouteImport } from './routes/sites/$siteId'
import { Route as SensorsSensorIdRouteImport } from './routes/sensors/$sensorId'
import { Route as SensorPlatformsSensorPlatformIdRouteImport } from './routes/sensor-platforms/$sensorPlatformId'
import { Route as SeasonsSeasonIdRouteImport } from './routes/seasons/$seasonId'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts/$scriptId'
import { Route as ProceduresProcedureIdRouteImport } from './routes/procedures/$procedureId'
import { Route as PopulationsPopulationIdRouteImport } from './routes/populations/$populationId'
import { Route as PlotsPlotIdRouteImport } from './routes/plots/$plotId'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as LinesLineIdRouteImport } from './routes/lines/$lineId'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as GenotypingStudiesStudyIdRouteImport } from './routes/genotyping-studies/$studyId'
import { Route as ExperimentsExperimentIdRouteImport } from './routes/experiments/$experimentId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as AccessionsAccessionIdRouteImport } from './routes/accessions/$accessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsIndexRoute = VariantsIndexRouteImport.update({
  id: '/variants/',
  path: '/variants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraitsIndexRoute = TraitsIndexRouteImport.update({
  id: '/traits/',
  path: '/traits/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsIndexRoute = SensorsIndexRouteImport.update({
  id: '/sensors/',
  path: '/sensors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorPlatformsIndexRoute = SensorPlatformsIndexRouteImport.update({
  id: '/sensor-platforms/',
  path: '/sensor-platforms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIndexRoute = ProceduresIndexRouteImport.update({
  id: '/procedures/',
  path: '/procedures/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationsIndexRoute = PopulationsIndexRouteImport.update({
  id: '/populations/',
  path: '/populations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIndexRoute = PlotsIndexRouteImport.update({
  id: '/plots/',
  path: '/plots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesIndexRoute = LinesIndexRouteImport.update({
  id: '/lines/',
  path: '/lines/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenotypingStudiesIndexRoute = GenotypingStudiesIndexRouteImport.update({
  id: '/genotyping-studies/',
  path: '/genotyping-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessionsIndexRoute = AccessionsIndexRouteImport.update({
  id: '/accessions/',
  path: '/accessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsVariantIdRoute = VariantsVariantIdRouteImport.update({
  id: '/variants/$variantId',
  path: '/variants/$variantId',
  getParentRoute: () => rootRouteImport,
} as any)
const TraitsTraitIdRoute = TraitsTraitIdRouteImport.update({
  id: '/traits/$traitId',
  path: '/traits/$traitId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsSensorIdRoute = SensorsSensorIdRouteImport.update({
  id: '/sensors/$sensorId',
  path: '/sensors/$sensorId',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorPlatformsSensorPlatformIdRoute =
  SensorPlatformsSensorPlatformIdRouteImport.update({
    id: '/sensor-platforms/$sensorPlatformId',
    path: '/sensor-platforms/$sensorPlatformId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeasonsSeasonIdRoute = SeasonsSeasonIdRouteImport.update({
  id: '/seasons/$seasonId',
  path: '/seasons/$seasonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresProcedureIdRoute = ProceduresProcedureIdRouteImport.update({
  id: '/procedures/$procedureId',
  path: '/procedures/$procedureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationsPopulationIdRoute = PopulationsPopulationIdRouteImport.update({
  id: '/populations/$populationId',
  path: '/populations/$populationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsPlotIdRoute = PlotsPlotIdRouteImport.update({
  id: '/plots/$plotId',
  path: '/plots/$plotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesLineIdRoute = LinesLineIdRouteImport.update({
  id: '/lines/$lineId',
  path: '/lines/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenotypingStudiesStudyIdRoute =
  GenotypingStudiesStudyIdRouteImport.update({
    id: '/genotyping-studies/$studyId',
    path: '/genotyping-studies/$studyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperimentsExperimentIdRoute = ExperimentsExperimentIdRouteImport.update({
  id: '/experiments/$experimentId',
  path: '/experiments/$experimentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessionsAccessionIdRoute = AccessionsAccessionIdRouteImport.update({
  id: '/accessions/$accessionId',
  path: '/accessions/$accessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessions/$accessionId': typeof AccessionsAccessionIdRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/genotyping-studies/$studyId': typeof GenotypingStudiesStudyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/plots/$plotId': typeof PlotsPlotIdRoute
  '/populations/$populationId': typeof PopulationsPopulationIdRoute
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/sensor-platforms/$sensorPlatformId': typeof SensorPlatformsSensorPlatformIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/traits/$traitId': typeof TraitsTraitIdRoute
  '/variants/$variantId': typeof VariantsVariantIdRoute
  '/accessions/': typeof AccessionsIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/files/': typeof FilesIndexRoute
  '/genotyping-studies/': typeof GenotypingStudiesIndexRoute
  '/import/': typeof ImportIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/populations/': typeof PopulationsIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/sensor-platforms/': typeof SensorPlatformsIndexRoute
  '/sensors/': typeof SensorsIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/traits/': typeof TraitsIndexRoute
  '/variants/': typeof VariantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessions/$accessionId': typeof AccessionsAccessionIdRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/genotyping-studies/$studyId': typeof GenotypingStudiesStudyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/plots/$plotId': typeof PlotsPlotIdRoute
  '/populations/$populationId': typeof PopulationsPopulationIdRoute
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/sensor-platforms/$sensorPlatformId': typeof SensorPlatformsSensorPlatformIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/traits/$traitId': typeof TraitsTraitIdRoute
  '/variants/$variantId': typeof VariantsVariantIdRoute
  '/accessions': typeof AccessionsIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/files': typeof FilesIndexRoute
  '/genotyping-studies': typeof GenotypingStudiesIndexRoute
  '/import': typeof ImportIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/lines': typeof LinesIndexRoute
  '/models': typeof ModelsIndexRoute
  '/plots': typeof PlotsIndexRoute
  '/populations': typeof PopulationsIndexRoute
  '/procedures': typeof ProceduresIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/sensor-platforms': typeof SensorPlatformsIndexRoute
  '/sensors': typeof SensorsIndexRoute
  '/sites': typeof SitesIndexRoute
  '/traits': typeof TraitsIndexRoute
  '/variants': typeof VariantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessions/$accessionId': typeof AccessionsAccessionIdRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/genotyping-studies/$studyId': typeof GenotypingStudiesStudyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/plots/$plotId': typeof PlotsPlotIdRoute
  '/populations/$populationId': typeof PopulationsPopulationIdRoute
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/sensor-platforms/$sensorPlatformId': typeof SensorPlatformsSensorPlatformIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/traits/$traitId': typeof TraitsTraitIdRoute
  '/variants/$variantId': typeof VariantsVariantIdRoute
  '/accessions/': typeof AccessionsIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/files/': typeof FilesIndexRoute
  '/genotyping-studies/': typeof GenotypingStudiesIndexRoute
  '/import/': typeof ImportIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/populations/': typeof PopulationsIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/sensor-platforms/': typeof SensorPlatformsIndexRoute
  '/sensors/': typeof SensorsIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/traits/': typeof TraitsIndexRoute
  '/variants/': typeof VariantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessions/$accessionId'
    | '/datasets/$datasetId'
    | '/experiments/$experimentId'
    | '/genotyping-studies/$studyId'
    | '/jobs/$jobId'
    | '/lines/$lineId'
    | '/models/$modelId'
    | '/plots/$plotId'
    | '/populations/$populationId'
    | '/procedures/$procedureId'
    | '/scripts/$scriptId'
    | '/seasons/$seasonId'
    | '/sensor-platforms/$sensorPlatformId'
    | '/sensors/$sensorId'
    | '/sites/$siteId'
    | '/traits/$traitId'
    | '/variants/$variantId'
    | '/accessions/'
    | '/datasets/'
    | '/experiments/'
    | '/files/'
    | '/genotyping-studies/'
    | '/import/'
    | '/jobs/'
    | '/lines/'
    | '/models/'
    | '/plots/'
    | '/populations/'
    | '/procedures/'
    | '/scripts/'
    | '/seasons/'
    | '/sensor-platforms/'
    | '/sensors/'
    | '/sites/'
    | '/traits/'
    | '/variants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessions/$accessionId'
    | '/datasets/$datasetId'
    | '/experiments/$experimentId'
    | '/genotyping-studies/$studyId'
    | '/jobs/$jobId'
    | '/lines/$lineId'
    | '/models/$modelId'
    | '/plots/$plotId'
    | '/populations/$populationId'
    | '/procedures/$procedureId'
    | '/scripts/$scriptId'
    | '/seasons/$seasonId'
    | '/sensor-platforms/$sensorPlatformId'
    | '/sensors/$sensorId'
    | '/sites/$siteId'
    | '/traits/$traitId'
    | '/variants/$variantId'
    | '/accessions'
    | '/datasets'
    | '/experiments'
    | '/files'
    | '/genotyping-studies'
    | '/import'
    | '/jobs'
    | '/lines'
    | '/models'
    | '/plots'
    | '/populations'
    | '/procedures'
    | '/scripts'
    | '/seasons'
    | '/sensor-platforms'
    | '/sensors'
    | '/sites'
    | '/traits'
    | '/variants'
  id:
    | '__root__'
    | '/'
    | '/accessions/$accessionId'
    | '/datasets/$datasetId'
    | '/experiments/$experimentId'
    | '/genotyping-studies/$studyId'
    | '/jobs/$jobId'
    | '/lines/$lineId'
    | '/models/$modelId'
    | '/plots/$plotId'
    | '/populations/$populationId'
    | '/procedures/$procedureId'
    | '/scripts/$scriptId'
    | '/seasons/$seasonId'
    | '/sensor-platforms/$sensorPlatformId'
    | '/sensors/$sensorId'
    | '/sites/$siteId'
    | '/traits/$traitId'
    | '/variants/$variantId'
    | '/accessions/'
    | '/datasets/'
    | '/experiments/'
    | '/files/'
    | '/genotyping-studies/'
    | '/import/'
    | '/jobs/'
    | '/lines/'
    | '/models/'
    | '/plots/'
    | '/populations/'
    | '/procedures/'
    | '/scripts/'
    | '/seasons/'
    | '/sensor-platforms/'
    | '/sensors/'
    | '/sites/'
    | '/traits/'
    | '/variants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessionsAccessionIdRoute: typeof AccessionsAccessionIdRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ExperimentsExperimentIdRoute: typeof ExperimentsExperimentIdRoute
  GenotypingStudiesStudyIdRoute: typeof GenotypingStudiesStudyIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  LinesLineIdRoute: typeof LinesLineIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  PlotsPlotIdRoute: typeof PlotsPlotIdRoute
  PopulationsPopulationIdRoute: typeof PopulationsPopulationIdRoute
  ProceduresProcedureIdRoute: typeof ProceduresProcedureIdRoute
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRoute
  SeasonsSeasonIdRoute: typeof SeasonsSeasonIdRoute
  SensorPlatformsSensorPlatformIdRoute: typeof SensorPlatformsSensorPlatformIdRoute
  SensorsSensorIdRoute: typeof SensorsSensorIdRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  TraitsTraitIdRoute: typeof TraitsTraitIdRoute
  VariantsVariantIdRoute: typeof VariantsVariantIdRoute
  AccessionsIndexRoute: typeof AccessionsIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  GenotypingStudiesIndexRoute: typeof GenotypingStudiesIndexRoute
  ImportIndexRoute: typeof ImportIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LinesIndexRoute: typeof LinesIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  PlotsIndexRoute: typeof PlotsIndexRoute
  PopulationsIndexRoute: typeof PopulationsIndexRoute
  ProceduresIndexRoute: typeof ProceduresIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  SeasonsIndexRoute: typeof SeasonsIndexRoute
  SensorPlatformsIndexRoute: typeof SensorPlatformsIndexRoute
  SensorsIndexRoute: typeof SensorsIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
  TraitsIndexRoute: typeof TraitsIndexRoute
  VariantsIndexRoute: typeof VariantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/': {
      id: '/variants/'
      path: '/variants'
      fullPath: '/variants/'
      preLoaderRoute: typeof VariantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traits/': {
      id: '/traits/'
      path: '/traits'
      fullPath: '/traits/'
      preLoaderRoute: typeof TraitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/': {
      id: '/sensors/'
      path: '/sensors'
      fullPath: '/sensors/'
      preLoaderRoute: typeof SensorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-platforms/': {
      id: '/sensor-platforms/'
      path: '/sensor-platforms'
      fullPath: '/sensor-platforms/'
      preLoaderRoute: typeof SensorPlatformsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/': {
      id: '/procedures/'
      path: '/procedures'
      fullPath: '/procedures/'
      preLoaderRoute: typeof ProceduresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/populations/': {
      id: '/populations/'
      path: '/populations'
      fullPath: '/populations/'
      preLoaderRoute: typeof PopulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/': {
      id: '/plots/'
      path: '/plots'
      fullPath: '/plots/'
      preLoaderRoute: typeof PlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/': {
      id: '/lines/'
      path: '/lines'
      fullPath: '/lines/'
      preLoaderRoute: typeof LinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genotyping-studies/': {
      id: '/genotyping-studies/'
      path: '/genotyping-studies'
      fullPath: '/genotyping-studies/'
      preLoaderRoute: typeof GenotypingStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessions/': {
      id: '/accessions/'
      path: '/accessions'
      fullPath: '/accessions/'
      preLoaderRoute: typeof AccessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants/$variantId': {
      id: '/variants/$variantId'
      path: '/variants/$variantId'
      fullPath: '/variants/$variantId'
      preLoaderRoute: typeof VariantsVariantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traits/$traitId': {
      id: '/traits/$traitId'
      path: '/traits/$traitId'
      fullPath: '/traits/$traitId'
      preLoaderRoute: typeof TraitsTraitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/$sensorId': {
      id: '/sensors/$sensorId'
      path: '/sensors/$sensorId'
      fullPath: '/sensors/$sensorId'
      preLoaderRoute: typeof SensorsSensorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-platforms/$sensorPlatformId': {
      id: '/sensor-platforms/$sensorPlatformId'
      path: '/sensor-platforms/$sensorPlatformId'
      fullPath: '/sensor-platforms/$sensorPlatformId'
      preLoaderRoute: typeof SensorPlatformsSensorPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$seasonId': {
      id: '/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof SeasonsSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/$procedureId': {
      id: '/procedures/$procedureId'
      path: '/procedures/$procedureId'
      fullPath: '/procedures/$procedureId'
      preLoaderRoute: typeof ProceduresProcedureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/populations/$populationId': {
      id: '/populations/$populationId'
      path: '/populations/$populationId'
      fullPath: '/populations/$populationId'
      preLoaderRoute: typeof PopulationsPopulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/$plotId': {
      id: '/plots/$plotId'
      path: '/plots/$plotId'
      fullPath: '/plots/$plotId'
      preLoaderRoute: typeof PlotsPlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$lineId': {
      id: '/lines/$lineId'
      path: '/lines/$lineId'
      fullPath: '/lines/$lineId'
      preLoaderRoute: typeof LinesLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genotyping-studies/$studyId': {
      id: '/genotyping-studies/$studyId'
      path: '/genotyping-studies/$studyId'
      fullPath: '/genotyping-studies/$studyId'
      preLoaderRoute: typeof GenotypingStudiesStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentId': {
      id: '/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof ExperimentsExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessions/$accessionId': {
      id: '/accessions/$accessionId'
      path: '/accessions/$accessionId'
      fullPath: '/accessions/$accessionId'
      preLoaderRoute: typeof AccessionsAccessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessionsAccessionIdRoute: AccessionsAccessionIdRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ExperimentsExperimentIdRoute: ExperimentsExperimentIdRoute,
  GenotypingStudiesStudyIdRoute: GenotypingStudiesStudyIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  LinesLineIdRoute: LinesLineIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  PlotsPlotIdRoute: PlotsPlotIdRoute,
  PopulationsPopulationIdRoute: PopulationsPopulationIdRoute,
  ProceduresProcedureIdRoute: ProceduresProcedureIdRoute,
  ScriptsScriptIdRoute: ScriptsScriptIdRoute,
  SeasonsSeasonIdRoute: SeasonsSeasonIdRoute,
  SensorPlatformsSensorPlatformIdRoute: SensorPlatformsSensorPlatformIdRoute,
  SensorsSensorIdRoute: SensorsSensorIdRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  TraitsTraitIdRoute: TraitsTraitIdRoute,
  VariantsVariantIdRoute: VariantsVariantIdRoute,
  AccessionsIndexRoute: AccessionsIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  GenotypingStudiesIndexRoute: GenotypingStudiesIndexRoute,
  ImportIndexRoute: ImportIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  LinesIndexRoute: LinesIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  PlotsIndexRoute: PlotsIndexRoute,
  PopulationsIndexRoute: PopulationsIndexRoute,
  ProceduresIndexRoute: ProceduresIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  SeasonsIndexRoute: SeasonsIndexRoute,
  SensorPlatformsIndexRoute: SensorPlatformsIndexRoute,
  SensorsIndexRoute: SensorsIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
  TraitsIndexRoute: TraitsIndexRoute,
  VariantsIndexRoute: VariantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
